apiVersion: v1
kind: Service
metadata:
  name: results-app-service
  labels:
    name: result-app-service
    author: hbc
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
  selector:
    name: result-app-service
    author: hbc