apiVersion: v1
kind: pod
metadata:
  name: voting-app-pod
  labels:
    name: voting-app-pod
    author: hbc
spec:
  containers:
    - name: voting-app
      image: dockersamples/examplevotingapp_vote
      ports:
        - containerPort: 80
...
