apiVersion: v1
kind: pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    author: hbc
spec:
  containers:
    - name: worker-app
      image: dockersamples/examplevotingapp_vote
...